### ISSUE TITLE
Update configuration for npm deployment with Travis CI before the next deployment

### ISSUE THREAD

**Issue by astorije** [w3c/insafe#10]
npm deployment has changed and building the next tagged commit will fail to deploy.

See [this sub-thread](https://github.com/travis-ci/travis-ci/issues/4197#issuecomment-123582302) for more information.

**Comment by tripu** [comment]
@guibbs, w3c/specberus#237 might come handy when you want to tackle this.

**Comment by tripu** [comment]
[Fixed](https://travis-ci.org/w3c/insafe/jobs/309443253)
