### ISSUE TITLE
New Top Level Domains don't work

### ISSUE THREAD

**Issue by guibbs** [w3c/insafe#8]
see https://github.com/w3c/Mobile-Checker/issues/115

**Comment by tripu** [comment]
@guibbs, I've been debugging this issue in Specberus, and I see that some of these new TLDs, eg `happyness.life`, return HTTP code `406`.

My proposed solution in Specberus (w3c/specberus#266) is simply to add that code to the custom list of accepted HTTP codes that is passed along to *insafe* from *Specberus*.

**Comment by tripu** [comment]
@guibbs, I suggest you either [do the same](https://github.com/w3c/specberus/pull/266) in Insafe (add `406` as an accepted code) or close this issue&hellip;

**Comment by guibbs** [comment]
406	Not Acceptable "This response is sent when the web server, after performing server-driven content negotiation, doesn't find any content following the criteria given by the user agent."

:|

**Comment by guibbs** [comment]
Im gonna add send a PR to Insafe but I don't really like that it returns 406

**Comment by tripu** [comment]
Maybe others in the team know why those domains send back that code, and whether that's acceptable&hellip; I'm pinging them on IRC.
